var searchData=
[
  ['factory_2ecpp_0',['factory.cpp',['../factory_8cpp.html',1,'']]],
  ['factory_2ehpp_1',['factory.hpp',['../factory_8hpp.html',1,'']]],
  ['fato_20de_20serem_20classes_20genéricas_2',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['feito_20em_20c_20com_20arquitetura_20orientada_20a_20objetos_3',['&amp;gt;Simulador de Dinãmica de Sistema inspirado no Vensim, feito em C++ com arquitetura orientada a objetos.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md1',1,'']]],
  ['fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_4',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['flow_5',['Flow',['../class_flow.html',1,'']]],
  ['flow_2ehpp_6',['flow.hpp',['../flow_8hpp.html',1,'']]],
  ['flowimpl_7',['FlowImpl',['../class_flow_impl.html',1,'FlowImpl'],['../class_flow_impl.html#afc694ee6bf220e266d6e0536c4b2b1fe',1,'FlowImpl::FlowImpl(std::string name=&quot;&quot;, System *origin=nullptr, System *destination=nullptr)'],['../class_flow_impl.html#a2981b1758ffef2310105758b4f473c27',1,'FlowImpl::FlowImpl(const FlowImpl &amp;obj)']]],
  ['flowimpl_2ecpp_8',['flowImpl.cpp',['../flow_impl_8cpp.html',1,'']]],
  ['flowimpl_2ehpp_9',['flowImpl.hpp',['../flow_impl_8hpp.html',1,'']]],
  ['flowiterator_10',['flowIterator',['../class_model.html#af19b499569caa4d43b69914002e04271',1,'Model']]],
  ['flows_11',['flows',['../class_model_impl.html#a8b029de6dc420bd98213c51997dd18ea',1,'ModelImpl']]],
  ['flows_20permite_20simular_20fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_12',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['fluxos_20flows_20permite_20simular_20fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_13',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['funcional_5ftests_2ecpp_14',['funcional_tests.cpp',['../funcional__tests_8cpp.html',1,'']]],
  ['funcional_5ftests_2ehpp_15',['funcional_tests.hpp',['../funcional__tests_8hpp.html',1,'']]]
];
