var searchData=
[
  ['c_20com_20arquitetura_20orientada_20a_20objetos_0',['&amp;gt;Simulador de Dinãmica de Sistema inspirado no Vensim, feito em C++ com arquitetura orientada a objetos.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md1',1,'']]],
  ['classes_20genéricas_1',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['cleardestination_2',['clearDestination',['../class_flow.html#aed69a437a33ee4981929c64fda6577fd',1,'Flow::clearDestination()'],['../class_flow_impl.html#adfd4fee8e1584051b41e30afc7ed13ce',1,'FlowImpl::clearDestination()']]],
  ['clearorigin_3',['clearOrigin',['../class_flow.html#ad13f6efcb706676ab4b9d5553203e3e0',1,'Flow::clearOrigin()'],['../class_flow_impl.html#a356b2f12732af3010c3096e543d504ed',1,'FlowImpl::clearOrigin()']]],
  ['com_20arquitetura_20orientada_20a_20objetos_4',['&amp;gt;Simulador de Dinãmica de Sistema inspirado no Vensim, feito em C++ com arquitetura orientada a objetos.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md1',1,'']]],
  ['com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_5',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_6',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['complexfuncionaltest_7',['complexFuncionalTest',['../funcional__tests_8cpp.html#a4e9f63b18e0833b74fd2513d758ee4da',1,'complexFuncionalTest(void):&#160;funcional_tests.cpp'],['../funcional__tests_8hpp.html#a943dfe0c597a01c9760c140715fed527',1,'complexFuncionalTest():&#160;funcional_tests.cpp']]],
  ['complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_8',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['conectadas_20por_20fluxos_20flows_20permite_20simular_20fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_9',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['createexponentialflow_10',['createExponentialFlow',['../factory_8cpp.html#ac5601319a801d7db0e821132f780afc4',1,'createExponentialFlow(std::string name, System *origin, System *destination):&#160;factory.cpp'],['../factory_8hpp.html#ae7635464d85ff48fb60b826c36fd7faf',1,'createExponentialFlow(std::string name=&quot;&quot;, System *origin=nullptr, System *destination=nullptr):&#160;factory.cpp']]],
  ['createlogisticflow_11',['createLogisticFlow',['../factory_8cpp.html#ae9cc27978cafd8b57f64dfbeb8cbc6a7',1,'createLogisticFlow(std::string name, System *origin, System *destination, double pMax):&#160;factory.cpp'],['../factory_8hpp.html#a321e99a6d2963a43057178b6c5b1a24f',1,'createLogisticFlow(std::string name=&quot;&quot;, System *origin=nullptr, System *destination=nullptr, double pMax=0.0):&#160;factory.cpp']]],
  ['createmodel_12',['createModel',['../factory_8cpp.html#ab6eb2892b3ab436a84a64e974780c361',1,'createModel():&#160;factory.cpp'],['../factory_8hpp.html#ab6eb2892b3ab436a84a64e974780c361',1,'createModel():&#160;factory.cpp']]],
  ['createsystem_13',['createSystem',['../factory_8cpp.html#addaddf7b22f1a83063e8571c7cf1cca6',1,'createSystem(std::string name, double value):&#160;factory.cpp'],['../factory_8hpp.html#aeaea0f9f206dccffb1513d9babc513dc',1,'createSystem(std::string name=&quot;&quot;, double value=0.0):&#160;factory.cpp']]],
  ['crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_14',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_15',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_16',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]]
];
