var searchData=
[
  ['e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_0',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['em_20c_20com_20arquitetura_20orientada_20a_20objetos_1',['&amp;gt;Simulador de Dinãmica de Sistema inspirado no Vensim, feito em C++ com arquitetura orientada a objetos.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md1',1,'']]],
  ['estado_20systems_20conectadas_20por_20fluxos_20flows_20permite_20simular_20fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_2',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['estrutura_20do_20projeto_3',['Estrutura do projeto',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md4',1,'Estrutura do projeto'],['../test.html#_test000001',1,'Estrutura do projeto']]],
  ['evolução_20temporal_20de_20variáveis_20de_20estado_20systems_20conectadas_20por_20fluxos_20flows_20permite_20simular_20fenômenos_20como_20crescimento_20exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_4',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]],
  ['exponencial_20crescimento_20logístico_20e_20sistemas_20complexos_20com_20múltiplas_20interações_20sendo_20possivel_20criar_20outras_20simulações_20pelo_20fato_20de_20serem_20classes_20genéricas_5',['&lt;b&gt;MyVensim&lt;/b&gt; é um simulador de dinâmica de sistemas que modela a evolução temporal de variáveis de estado (&lt;b&gt;Systems&lt;/b&gt;) conectadas por fluxos (&lt;b&gt;Flows&lt;/b&gt;). Permite simular fenômenos como crescimento exponencial, crescimento logístico e sistemas complexos com múltiplas interações. Sendo possivel criar outras simulações, pelo fato de serem classes genéricas.',['../C:/Users/Pedro/Documents/4periodo/EngSoftware_1/Sprint5/MyVensim/README.md#autotoc_md3',1,'']]]
];
